name: Hello world!

on:
  push:
    branches:
      - develop

jobs:
  hello-world:
    name: Hello world!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello world!
        uses: ./hello-world-composite
        with:
          name: Geir
    